### ISSUE TITLE
Indirect object syntax does not work when Crypt::Skip32::XS is installed

### ISSUE THREAD

**Issue by johnlaur** [alestic/Crypt-Skip32#1]
Indirect object syntax does not work when Crypt::Skip32 defers to Crypt::Skip32::XS

Breaks:
```
my $crypto = new Crypt::Skip32 $key;
```

Works:
```
my $cypto = Crypt::Skip32->new($key);
```

Two comments about this. First is that indirect notation [should be discouraged](http://modernperlbooks.com/mt/2009/08/the-problems-with-indirect-object-notation.html), so the documentation could be updated to reflect that. That being said, it would be nice to have an implementation that does not have a regression when it switches to using the XS module even if one is not using best practices.

See also: https://rt.cpan.org/Public/Bug/Display.html?id=98567

**Comment by ehammond** [comment]
Thanks for taking the time to investigate and report this.

I'd be happy to review a PR.

**Comment by ehammond** [comment]
https://github.com/gray/crypt-skip32-xs
CC: @gray

**Comment by johnlaur** [comment]
I’ll be happy to submit a patch but I’d like to see if there is some consensus or best practice for how to go about this.  Since you don’t really specify a functional interface it would be easy to have the new method take care of things but you may not want this behavior.  I’ll investigate some similar packages such as JSON::MaybeXS and report back.
